name: Bump image tag
description: Bump image tag in kustomizations file
inputs:
  dockerfile-dir:
    description: directory containing the Dockerfile generating the image
    required: true
  push:
    description: Do you want to push the changes?
    required: true
    default: true
  registry:
    description: Registry DNS name
    required: true
  git-commit-user:
    description: User used for bump commits
    required: true
  git-commit-email:
    description: Email used for bump commits
    required: true
  base-path:
    description: Location of kubernetes base folder
    required: true
    default: infrastructure/kubernetes/base
runs:
  using: "composite"
  steps:
    - name: generate image name and version
      id: image
      run: |
        DIR=${{ inputs.dockerfile-dir }}
        SHA="${{ github.event.pull_request.head.sha }}"
        TAG="$(date '+%Y-%m-%d-%H-%M-%S')_${SHA:0:7}"
        echo "::set-output name=name::${DIR/s\//_}"
        echo "::set-output name=tag::$TAG"
      shell: bash
    - name: Bump image
      run: |
        APP=$(echo '${{ steps.image.outputs.name }}' | cut -d '_' -f2-)
        TYPE=$(echo '${{ steps.image.outputs.name }}' | cut -d '_' -f1)
        IMAGE="${{ inputs.registry }}/${{ steps.image.outputs.name }}:${{ steps.image.outputs.tag }}"
        yq -i -e "select( .metadata.name == \"${APP}\").spec.values.image |= \"${IMAGE}\"" "${{ inputs.base-path }}/${TYPE}s.yaml"
      shell: bash
    - name: commit versions
      run: |
        git config --global user.name "${{ inputs.git-commit-user }}"
        git config --global user.email "${{ inputs.git-commit-email }}"
        git commit -am ':robot: auto bump image tag for ${{ steps.image.outputs.name }}'
      shell: bash
    - name: push
      if: inputs.push == 'true'
      run: git push
      shell: bash
