name: Validate Job
description: Run Job tests and linter
inputs:
  gcp-service-account-key:
    description: GCP Service Account Key (JSON format)
    required: true
  python-version:
    description: Python Version
    required: true
  python-dm:
    description: "Python dependency management tool, accepted values: [poetry, pip-tools]"
    required: true
    default: poetry
  working-directory:
    description: Location of python root folder
    required: true
  integration:
    description: do you want to run integration tests?
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ inputs.gcp-service-account-key }}
        export_default_credentials: true
    - name: Install Python
      uses: actions/setup-python@v2.3.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install Dependency management
      run: |
        python -m pip install --upgrade pip
        python -m pip install ${{ inputs.python-dm }}
        if [[ "${{ inputs.python-dm }}" == "poetry" ]]; then
          poetry config virtualenvs.create false
        fi
      shell: bash
    - name: Install Python dependencies
      working-directory: ${{ inputs.working-directory }}
      run: |
        make compile
        make install-dev
      shell: bash
    - name: Run Lint
      working-directory: ${{ inputs.working-directory }}
      run: make lint
      shell: bash
    - name: Run tests with coverage
      working-directory: ${{ inputs.working-directory }}
      run: make coverage
      shell: bash
    - name: Run integration tests
      if: inputs.integration == 'true'
      working-directory: ${{ inputs.working-directory }}
      run: make integration
      shell: bash
