name: Validate Graddle Application
description: Run Application Tests and Linter
inputs:
  gcp-service-account-key:
    description: GCP Service Account Key (JSON format)
    required: true
  java-version:
    description: java version
    required: true
  working-directory:
    description: Path of the folder containing the Dockerfile
    required: true
    default: app
  integration:
    description: do you want to run integration tests?
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ inputs.gcp-service-account-key }}
        export_default_credentials: true
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}
    - name: Compile
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew build -x test -x integration -x spotlessCheck
      shell: bash
    - name: Run Linter
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew spotlessCheck
      shell: bash
    - name: Run Test with Coverage
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew jacocoTestVerification
      shell: bash
    - name: Run Integration Tests
      if: inputs.integration == 'true'
      working-directory: ${{ inputs.working-directory }}
      run: ./gradlew integration
      shell: bash
