name: Files Changes Info
description: Get files changes info
inputs:
  base-sha:
    description: base sha for changes
    required: true
  terragrunt-root-directory:
    description: Terragrunt root directory
    required: true
    default: infrastructure/terragrunt
  apps-directory:
    description: App root directory
    required: true
    default: apps
  jobs-directory:
    description: Jobs Directory
    required: true
    default: jobs
  cloud-functions-directory:
    description: Cloud functions root directory
    required: true
    default: cloud_functions
  kubernetes-root-directory:
    description: Kubernetes root directory
    required: true
    default: infrastructure/kubernetes
  kubernetes-base-directory:
    description: Base directory within kubernetes-root-directory
    required: true
    default: base
  kubernetes-overlays-directory:
    description: Overlays directory within kubernetes-root-directory
    required: true
    default: overlays
outputs:
  terragrunt-base-changes:
    description: Did Terragrunt base file changed?
    value: ${{ steps.terragrunt-base-changes.outputs.any_modified }}
  terragunt-dev-config-changes:
    description: Did Terragrunt dev config change?
    value: ${{ steps.terragunt-dev-config-changes.outputs.any_modified }}
  terragunt-live-config-changes:
    description: Did Terragrunt live config change?
    value: ${{ steps.terragunt-live-config-changes.outputs.any_modified }}
  apps-changes:
    description: Did any apps change?
    value: ${{ steps.apps-changes.outputs.any_modified }}
  apps-list-changes:
    description: List of app that changed (JSON FORMAT)
    value: ${{ steps.apps-list-changes.outputs.value }}
  jobs-changes:
    description: List of jobs files that changed (JSON FORMAT)
    value: ${{ steps.jobs-changes.outputs.any_modified }}
  jobs-list-changes:
    description: Did any cloud functions app change?
    value: ${{ steps.jobs-list-changes.outputs.value }}
  cloud-functions-changes:
    description: Did any cloud functions app change?
    value: ${{ steps.cloud-functions-changes.outputs.any_modified }}
  cloud-functions-list-changes:
    description: List of cloud function files that changed (JSON FORMAT)
    value: ${{ steps.cloud-functions-list-changes.outputs.value }}
  kubernetes-changes-overlay-dev:
    description: Did kubernetes dev overlay change?
    value: ${{ steps.kubernetes-changes-overlay-dev.outputs.any_modified }}
  kubernetes-changes-overlay-live:
    description: Did kubernetes live overlay change?
    value: ${{ steps.kubernetes-changes-overlay-live.outputs.any_modified }}
  kubernetes-changes-base:
    description: Did kubernetes base change?
    value: ${{ steps.kubernetes-changes-base.outputs.any_modified }}
  last-author:
    description: get the last commit author
    value: ${{ steps.last-author.outputs.value }}
runs:
  using: "composite"
  steps:
    - name: check terragrunt base changes
      id: terragrunt-base-changes
      uses: tj-actions/changed-files@v23
      with:
        files: |
          ${{ inputs.terragrunt-root-directory }}/**
        files_ignore: |
          ${{ inputs.terragrunt-root-directory }}/.gitignore
          ${{ inputs.terragrunt-root-directory }}/vars/**
        base_sha: ${{ inputs.base-sha }}
    - name: check terragrunt dev config changes
      id: terragunt-dev-config-changes
      uses: tj-actions/changed-files@v23
      with:
        files: |
          ${{ inputs.terragrunt-root-directory }}/vars/dev.yaml
        base_sha: ${{ inputs.base-sha }}
    - name: check terragrunt live config changes
      id: terragunt-live-config-changes
      uses: tj-actions/changed-files@v23
      with:
        files: |
          ${{ inputs.terragrunt-root-directory }}/vars/live.yaml
        base_sha: ${{ inputs.base-sha }}
    - name: check any apps changes
      id: apps-changes
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.apps-directory }}/**
        files_ignore: |
          ${{ inputs.apps-directory }}/README.md
          ${{ inputs.apps-directory }}/.gitignore
        base_sha: ${{ inputs.base-sha }}
    - name: get list of apps that changed
      id: apps-list-changes
      run: |
        while IFS= read -r change; do
          echo $change | cut -d '/' -f2 >> /tmp/list
        done <<< $(echo "${{ steps.apps-changes.outputs.all_changed_and_modified_files }}" | tr " " "\n")
        FOLDER_LIST='{ "app": [ '
        while IFS= read -r app; do
          if [[ ! -z "$app" ]]; then
            FOLDER_LIST="${FOLDER_LIST} \"${app}\","
          fi
        done <<< "$(cat /tmp/list | uniq)"
        FOLDER_LIST="${FOLDER_LIST:0:-1} ] }"
        FOLDER_LIST=$(echo $FOLDER_LIST | jq -c .)
        echo "::set-output name=value::${FOLDER_LIST}"
      shell: bash
    - name: check any jobs have changed
      id: jobs-changes
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.jobs-directory }}/**
        files_ignore: |
          ${{ inputs.jobs-directory }}/README.md
          ${{ inputs.jobs-directory }}/.gitignore
        base_sha: ${{ inputs.base-sha }}
    - name: get list of job files that changed
      id: jobs-list-changes
      run: |
        while IFS= read -r change; do
          echo $change | cut -d '/' -f2 >> /tmp/joblist
        done <<< $(echo "${{ steps.jobs-changes.outputs.all_changed_and_modified_files }}" | tr " " "\n")
        FOLDER_LIST='{ "job": [ '
        while IFS= read -r job; do
          if [[ ! -z "job" ]]; then
            FOLDER_LIST="${FOLDER_LIST} \"${job}\","
          fi
        done <<< "$(cat /tmp/joblist | uniq)"
        FOLDER_LIST="${FOLDER_LIST:0:-1} ] }"
        FOLDER_LIST=$(echo $FOLDER_LIST | jq -c .)
        echo "::set-output name=value::${FOLDER_LIST}"
      shell: bash
    - name: check any cloud function changes
      id: cloud-functions-changes
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.cloud-functions-directory }}/**
        base_sha: ${{ inputs.base-sha }}
    - name: get list of cloud function that changed
      id: cloud-functions-list-changes
      run: |
        while IFS= read -r change; do
          echo $change | cut -d '/' -f2 >> /tmp/functionlist
        done <<< $(echo "${{ steps.cloud-functions-changes.outputs.all_changed_and_modified_files }}" | tr " " "\n")
        FOLDER_LIST='{ "function": [ '
        while IFS= read -r function; do
          if [[ ! -z "$function" ]]; then
            FOLDER_LIST="${FOLDER_LIST} \"${function}\","
          fi
        done <<< "$(cat /tmp/functionlist | uniq)"
        FOLDER_LIST="${FOLDER_LIST:0:-1} ] }"
        FOLDER_LIST=$(echo $FOLDER_LIST | jq -c .)
        echo "::set-output name=value::${FOLDER_LIST}"
      shell: bash
    - name: check kubernetes changes overlay dev
      id: kubernetes-changes-overlay-dev
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.kubernetes-root-directory }}/${{ inputs.kubernetes-overlays-directory }}/dev/**
        base_sha: ${{ inputs.base-sha }}
    - name: check kubernetes changes overlay live
      id: kubernetes-changes-overlay-live
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.kubernetes-root-directory }}/${{ inputs.kubernetes-overlays-directory }}/live/**
        base_sha: ${{ inputs.base-sha }}
    - name: check kubernetes changes base
      id: kubernetes-changes-base
      uses: tj-actions/changed-files@v23
      with:
        files: ${{ inputs.kubernetes-root-directory }}/${{ inputs.kubernetes-base-directory }}/**
        base_sha: ${{ inputs.base-sha }}
    - name: get last author
      id: last-author
      run: echo "::set-output name=value::$(git log -1 --pretty=format:'%an')"
      shell: bash
