name: Create Draft Release
description: Create a RC branch and draft release associated to it
runs:
  using: "composite"
  steps:
    - name: create draft release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        SHA="${{ github.sha }}"
        TITLE="RC_$(date '+%Y-%m-%d-%H-%M-%S')_${SHA:0:7}"
        gh release create "CHANGE_ME_TO_SEMVER" \
          --generate-notes \
          --title "${TITLE}" \
          --target "${SHA}" \
          --draft
      shell: bash
